### ISSUE TITLE
How did you get it in electron preload.js  Used in ffmpeg.wasm

### ISSUE THREAD

**Issue by Hunlongyu** [mmamedel/ffmpegwasm-electron-test#1]
https://github.com/ffmpegwasm/ffmpeg.wasm/issues/85

Can you show me how to work in the preload.js  Used in ffmpeg.wasm

**Comment by mmamedel** [comment]
Repo updated. If you check the commit history you will notice that I turned off node integration, then I added code both in the Electron side and app side to access the Node.js child_process.execSync using a preload script.

You will notice that after the transcode is done successfully using ffmpeg.js the app running from Electron will open the Electron website (I used the "start" command, so should work only in Windows... you can replace with your OS specific). In the browser nothing happens because the code checks if window.electron exists (which is only created by the preload script when using Electron).

Hope this solves this issue.
